---
# /*---------------------------------------------------------------------------8
# |                                                                            |
# | This file runs common pre-provisioning tasks before the                    |
# | OS specific clustering is performed                                        |
# |                                                                            |
# +------------------------------------4--------------------------------------*/

- name:                                Ensure systemctl daemon is reloaded
  ansible.builtin.systemd:
    daemon_reload:                     true

# Configure SSH Keys for inter-node communication as root
- name:                                Ensure there are SSH keys for the root user to communicate between nodes
  ansible.builtin.command:             ssh-keygen -b 4096 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates:                           /root/.ssh/id_rsa

- name:                                Ensure there is a public key for the root user SSH key
  ansible.builtin.shell:               ssh-keygen -f /root/.ssh/id_rsa -y > /root/.ssh/id_rsa.pub
  args:
    creates:                           /root/.ssh/id_rsa.pub

- name:                                Ensure the Public SSH keys are available for exchanging SSH key trust between nodes
  ansible.builtin.command:               cat /root/.ssh/id_rsa.pub
  register:                            cluster_public_ssh_key
  changed_when:                        false

- name:                                Ensure the Primary Node public key is authorized on all nodes, required for crm_clustering
  ansible.builtin.authorized_key:
    user:                              root
    key:                               "{{ hostvars[primary_instance_name].cluster_public_ssh_key.stdout }}"

- name:                                Ensure the Secondary Node public key is authorized on all nodes, required for crm_clustering
  ansible.builtin.authorized_key:
    user:                              root
    key:                               "{{ hostvars[secondary_instance_name].cluster_public_ssh_key.stdout }}"


# Clustering commands are based on the Host OS
- name:                                "Cluster based on OS on VM {{ ansible_hostname }}"
  include_tasks:                       "1.17.2.0-cluster-{{ ansible_os_family }}.yml"
  when:                                cluster_existence_check != 0

# HLI not in scope for the MVP release
# - name: Ensure cluster is configured in Large Instance
#  include_tasks: "cluster-{{ ansible_os_family }}-large-instance.yml"
#  when:
#    - hdb_size == "LargeInstance"
#    - ansible_os_family == "Suse"
