---

# sapcontrol EXITCODES
#     0  Last webmethod call successful
#     1  Last webmethod call failed, invalid parameter
#     2  StartWait, StopWait, WaitforStarted, WaitforStopped, RestartServiceWait
#        timed out
#        CheckSystemCertificates detected warnings
#     3  GetProcessList succeeded, all processes running correctly
#        CheckSystemCertificates detected errors
#     4  GetProcessList succeeded, all processes stopped

- name: HSR - Determine if HANA is stopped
  become_user: "{{ db_sid_admin_user }}"
  ansible.builtin.shell: >
    source ~/.bashrc ;
    {{ sapcontrol_command }} -function GetProcessList
  failed_when: false
  changed_when: false
  register: hana_stopped

- name: HSR - Ensure HANA is stopped
  become_user: "{{ db_sid_admin_user }}"
  ansible.builtin.shell: >
    source ~/.bashrc ;
    {{ sapcontrol_command }} -function StopWait {{ hana_stop_start_timeout_in_seconds }} {{ hana_stop_start_delay_in_seconds }}
  when: hana_stopped.rc != 4

- name: HSR - Check HANA is stopped
  become_user: "{{ db_sid_admin_user }}"
  ansible.builtin.shell: >
    source ~/.bashrc ;
    {{ sapcontrol_command }} -function GetProcessList
  changed_when: false
  register: hana_stopped
  failed_when: hana_stopped.rc != 4
