---

# -------------------------------------+---------------------------------------8
#
# Description:  Validation for Prerequisites
#


- name:                                "Check required variables are present and not empty"
  ansible.builtin.assert:
    that:
      - "sapbits_location_base_path is defined"                                 # Has the variable been defined
      - "sapbits_location_base_path | trim | length != 0"                       #   and given a value

      - "sapbits_bom_files is defined"                                          # Has the variable been defined
      - "sapbits_bom_files | trim | length != 0"                                #   and given a value

      - "bom_base_name is defined"                                              # Has the variable been defined
      - "bom_base_name | trim | length != 0"                                    #   and given a value

      - "target_media_location is defined"                                      # Has the variable been defined
      - "target_media_location | trim | length != 0"                            #   and given a value
# -------------------------------------+---------------------------------------8

...
